export const NOTIFICATION_REPOSITORY_PROVIDE = Symbol('NOTIFICATION_REPOSITORY_PROVIDE');
export const NOTIFICATION_SERVICE_PROVIDE = Symbol('NOTIFICATION_SERVICE_PROVIDE');

export const NOTIFICATION_CREATE_USE_CASE_PROVIDE = Symbol('NOTIFICATION_CREATE_USE_CASE_PROVIDE');
export const NOTIFICATION_GET_USE_CASE_PROVIDE = Symbol('NOTIFICATION_GET_USE_CASE_PROVIDE');
export const NOTIFICATION_GET_ALL_USE_CASE_PROVIDE = Symbol(
  'NOTIFICATION_GET_ALL_USE_CASE_PROVIDE',
);
export const NOTIFICATION_UPDATE_USE_CASE_PROVIDE = Symbol('NOTIFICATION_UPDATE_USE_CASE_PROVIDE');
export const NOTIFICATION_DELETE_USE_CASE_PROVIDE = Symbol('NOTIFICATION_DELETE_USE_CASE_PROVIDE');
export const NOTIFICATION_MARK_AS_READ_USE_CASE_PROVIDE = Symbol(
  'NOTIFICATION_MARK_AS_READ_USE_CASE_PROVIDE',
);
export const NOTIFICATION_MARK_ALL_AS_READ_USE_CASE_PROVIDE = Symbol(
  'NOTIFICATION_MARK_ALL_AS_READ_USE_CASE_PROVIDE',
);
