export const USER_REPOSITORY_PROVIDE = 'USER_REPOSITORY_PROVIDE';
export const USER_INFRASTRUCTURE_SERVICE_PROVIDE = 'USER_INFRASTRUCTURE_SERVICE_PROVIDE';
export const USER_CREATE_USE_CASE_PROVIDE = 'USER_CREATE_USE_CASE_PROVIDE';
export const USER_SERVICE_PROVIDE = 'USER_SERVICE_PROVIDE';
