export enum UserErrorCode {
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  DUPLICATE_CPF = 'DUPLICATE_CPF',
  DUPLICATE_RG = 'DUPLICATE_RG',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
}
